### ISSUE TITLE
[Story] Can you open the repo as `triage access` ?

### ISSUE THREAD

**Issue by ShawnSun1031** [boyonglin/google-maps-extension#3]
FYI: https://docs.github.com/en/organizations/managing-user-access-to-your-organizations-repositories/managing-repository-roles/repository-roles-for-an-organization

If you use `triage access`, I can apply the tag to the issue. Thanks

**Comment by ShawnSun1031** [comment]
If using tags, we can classify the issues properly.
![image](https://github.com/boyonglin/google-maps-extension/assets/82211039/cf243207-784d-4ad5-bc40-2821b823e6ba)

**Comment by boyonglin** [comment]
Too bad, but it seems to be only available for GitHub Enterprise Cloud Organization.
